import type { SkillSummary } from '../../types';

const CONCEPTS = 'Identify AI concepts and capabilities';
const FOUNDRY = 'Implement AI solutions by using Microsoft Foundry';

export const skillSummaries: Record<string, SkillSummary> = {
  'Describe principles of responsible AI': {
    skill: 'Describe principles of responsible AI',
    bullets: [
      'Fairness: AI systems must treat all groups equitably; systematically biased outcomes for a demographic group violate it.',
      'Reliability and safety: systems must work correctly and consistently and fail safely — express uncertainty instead of guessing.',
      'Privacy and security: protect personal data through the lifecycle; anonymize training data, restrict access, and log usage.',
      'Inclusiveness: design for everyone — diverse languages, accents, abilities, and backgrounds must appear in training and testing.',
      'Transparency: users should know when they interact with AI and understand its decisions and limitations.',
      'Accountability: people, not AI, are accountable for outcomes; a named owner with approval and monitoring duties implements it.',
      'Apply fairness: measure outcomes per demographic group (disaggregated metrics) and retrain with balanced data to correct bias.',
      'Apply reliability: monitor outputs in production, force the model to signal confidence, and test with out-of-range inputs.',
      'Apply privacy: minimize personal data, anonymize before training, and grant access only to approved engineers with audit logs.',
      'Apply transparency: publish model cards documenting capabilities, limitations, and intended use of each released model.',
      'The six principles guide every stage: design, training, deployment, and monitoring — not only the model itself.',
      'Governance operationalizes the principles: policies, named owners, and audit trails make responsible AI enforceable.',
    ],
    sourceUrl: 'https://learn.microsoft.com/en-us/azure/ai-services/responsible-use-of-ai-overview',
  },
  'Identify AI model components and configurations': {
    skill: 'Identify AI model components and configurations',
    bullets: [
      'Tokens: the small units of text a generative model works with; it predicts the most probable next token at each step.',
      'Context window: the maximum input a model can consider at once; larger windows accept bigger documents but cost more.',
      'Temperature: controls randomness — low values give deterministic, focused outputs; high values increase creativity.',
      'Max tokens: caps the length of the generated response; a low limit can truncate long answers.',
      'Top-p (nucleus sampling): keeps only the smallest set of tokens whose cumulative probability reaches p, shaping output variety.',
      'System prompt: sets the assistant\'s role, tone, format, and constraints before any user input; the user prompt carries the request.',
      'Model families: text-only LLMs, multimodal models (text + image + audio), embedding models, and image-generation models.',
      'Multimodal models: accept text, images, and audio in one call and reason across modalities, such as answering about a photo.',
      'Embedding models: convert text into numeric vectors; semantic similarity is vector distance, the basis of meaning-based search.',
      'Serverless deployments: pay per token with automatic scaling — suited to variable, low-volume, or bursty usage.',
      'Provisioned throughput: reserves dedicated capacity at predictable cost — suited to sustained or peak-heavy, scheduled usage.',
      'A deployment is a hosted, callable endpoint for a specific model version; clients call it with an endpoint, name, and credential.',
    ],
    sourceUrl: 'https://learn.microsoft.com/en-us/azure/ai-foundry/what-is-ai-foundry',
  },
  'Identify AI workloads': {
    skill: 'Identify AI workloads',
    bullets: [
      'Text analysis: techniques over written text — sentiment classification, entity detection, keyword extraction, language detection, summarization.',
      'Sentiment analysis: labels text as positive, neutral, or negative; it measures emotional tone, not entities or topics.',
      'Entity detection: finds and classifies named entities in text, such as organizations, people, and locations.',
      'Keyword extraction: identifies the salient terms of a document, useful for topic indexes and grouping.',
      'Language detection: identifies the language of a message before routing or translation workflows.',
      'Speech recognition: converts spoken audio into text — call transcripts, meeting notes, and voice commands.',
      'Speech synthesis: converts text into spoken audio with natural voices for alerts, notifications, and accessibility.',
      'Speech translation: recognizes speech and outputs text in another language — live multilingual subtitles.',
      'Computer vision: analyzes images and video — object detection, image classification, OCR, facial recognition, and segmentation.',
      'OCR: extracts text from images — license plates, scanned documents, and screenshots.',
      'Image generation: creates new images from text prompts, such as product photos and marketing banners.',
      'Agentic AI: a model combined with tools (file search, code interpreter, APIs) that plans and executes multi-step tasks with autonomy.',
      'Information extraction: pulls structured fields from documents, forms, images, audio, and video.',
      'Match the capability to the modality: text in → text analysis; audio in → speech; image in → vision; content out → generation.',
    ],
    sourceUrl: 'https://learn.microsoft.com/en-us/azure/ai-services/what-are-ai-services',
  },
  'Implement generative AI apps and agents by using Foundry': {
    skill: 'Implement generative AI apps and agents by using Foundry',
    bullets: [
      'Foundry project: the workspace container for models, deployments, agents, and connections to data and APIs.',
      'Chat playground: test a deployed model with prompts and parameters before writing application code.',
      'Deploy a model from the model catalog; the deployment exposes an endpoint that clients call.',
      'Lightweight chat clients: call the deployment via the Foundry SDK with the endpoint, deployment name, and credentials.',
      'Effective system prompts define the role, tone, output format, and constraints; few-shot examples teach a specific format.',
      'Credentials belong in environment variables or secret stores — never in client code, repositories, or shared chats.',
      'Agents combine a model with tools (file/knowledge search, code interpreter, API connections) and instructions around a goal.',
      'Agent conversations run on threads; each user message starts a run that may call tools several times before the final answer.',
      'File search tool: retrieves documents for the agent; apply permissions on the tool and its data source so users only see what they may.',
      'Code interpreter: executes code in a sandbox for calculations, scripts, and data transformations during a conversation.',
      'Agent definition: model + tools + instructions; test the agent in the conversation pane before integrating it into the app.',
      'Fixed, step-by-step approval flows with no AI judgment belong in deterministic workflows, not in agents.',
    ],
    sourceUrl: 'https://learn.microsoft.com/en-us/azure/ai-foundry/agents/overview',
  },
  'Implement AI solutions for text and speech by using Foundry': {
    skill: 'Implement AI solutions for text and speech by using Foundry',
    bullets: [
      'Text analysis in Foundry: call a model deployment with a prompt that requests the label, entity, or summary you need.',
      'Sentiment over free text: a lightweight app sends each survey response to the deployment and receives the sentiment label.',
      'Multimodal audio input: short conversational questions can be spoken to a multimodal model, which answers in text.',
      'Azure Speech: speech-to-text and text-to-speech, available through the Speech SDK or Foundry Tools.',
      'Speech-to-text: transcribes calls, meetings, and microphone audio; accepts common formats such as WAV, MP3, and OGG.',
      'Speech SDK: stream audio to the service and receive transcriptions; requires a Speech resource with its region and a credential.',
      'Speaker diarization: segments audio by speaker so transcripts label who said each sentence.',
      'Speech translation: live subtitles in each participant\'s language for multilingual video meetings.',
      'Text-to-speech: announces alerts or reads notifications with neural voices; SSML tunes prosody and pronunciation.',
      'Custom speech: train a model on the domain vocabulary and acoustics to transcribe technical or noisy audio accurately.',
      'Streaming vs batch: streaming transcription serves near-real-time needs; batch transcription fits post-hoc archives.',
      'Max tokens enforces length: cap the output to keep summaries within a fixed word budget.',
    ],
    sourceUrl: 'https://learn.microsoft.com/en-us/azure/ai-services/speech-service/overview',
  },
  'Implement AI solutions with computer vision and image-generation capabilities by using Foundry': {
    skill: 'Implement AI solutions with computer vision and image-generation capabilities by using Foundry',
    bullets: [
      'Multimodal vision: send the image together with the text prompt to a deployed multimodal model to describe or answer about it.',
      'REST image input: embed the image as base64 in the request body alongside the text prompt.',
      'Image generation: creates new images from text prompts — product drafts, marketing banners, and concept visuals.',
      'Image size parameter: controls the output dimensions of generated images; quality settings trade fidelity against cost.',
      'OCR at scale: a dedicated OCR service extracts printed text from thousands of scanned documents efficiently.',
      'Object detection: locates objects in images with bounding boxes; image classification labels the entire image.',
      'Segmentation: labels each pixel to outline the exact boundary of every object in an image.',
      'Chart and photo Q&A: multimodal models read charts and answer questions about their content — suited to open questions, not batch OCR.',
      'Accessibility: multimodal models generate text descriptions (alt text) for uploaded photos.',
      'Content filters block harmful generated images; provenance metadata such as C2PA labels marks images as AI-generated.',
      'Ground vision answers: describe only what is visible in the image and flag uncertainty to avoid hallucinated details.',
      'Consistent inspection: a fixed rubric plus human review for uncertain cases yields accurate, auditable verdicts at scale.',
    ],
    sourceUrl: 'https://learn.microsoft.com/en-us/azure/ai-foundry/model-catalog/model-catalog-overview',
  },
  'Implement AI solutions for information extraction by using Foundry': {
    skill: 'Implement AI solutions for information extraction by using Foundry',
    bullets: [
      'Content Understanding: extracts structured fields from documents, forms, images, audio, and video.',
      'Analyzers: define the fields to extract from a given input type; applications call them via REST API or SDK.',
      'Document and forms extraction: reads fields with OCR — supplier names, invoice numbers, amounts, and due dates.',
      'Image extraction: handles scanned documents and photos that contain text to be captured as fields.',
      'Audio and video extraction: transcribes speech with time-stamped segments and speaker identification.',
      'Table extraction: captures pricing tables and similar content row by row inside document analyzers.',
      'Output shape: the analyzer returns a structured JSON object with the configured fields, ready for downstream systems.',
      'Integration flow: create a project, create the analyzer, define fields, test with samples, then integrate into the application.',
      'Fixed fields at scale: Content Understanding excels at repeatable extraction (for example, 2,000 invoices per month).',
      'Analyzers are configured once; they are not trained per call, and provisioned GPU capacity is an optional scaling choice.',
      'Contract example: party names and contract value are returned as JSON fields that the app consumes directly.',
      'Compliance example: decisions, speakers, and the minute each was made are extracted from recorded meetings.',
    ],
    sourceUrl: 'https://learn.microsoft.com/en-us/azure/ai-services/content-understanding/overview',
  },
};

export const skillDomains: Record<string, string> = {
  'Describe principles of responsible AI': CONCEPTS,
  'Identify AI model components and configurations': CONCEPTS,
  'Identify AI workloads': CONCEPTS,
  'Implement generative AI apps and agents by using Foundry': FOUNDRY,
  'Implement AI solutions for text and speech by using Foundry': FOUNDRY,
  'Implement AI solutions with computer vision and image-generation capabilities by using Foundry': FOUNDRY,
  'Implement AI solutions for information extraction by using Foundry': FOUNDRY,
};
