import type { QuestionSeed } from './types';

const STUDY_GUIDE = 'https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-104';

const DOMAINS = {
  ID: 'Identity and Governance',
  ST: 'Storage',
  CO: 'Compute',
  NW: 'Networking',
  MO: 'Monitoring and Recovery',
} as const;

const CASE_STUDY_PROMPT = `## Case Study: Contoso Ltd. Cloud Migration

Contoso Ltd. is migrating on-premises infrastructure to Azure. Current environment:

- On-premises Active Directory domain contoso.local
- Windows file server with 5 TB of department shares
- Three-tier web application (frontend, API, database) running on VMware
- VPN appliance for remote access

**Requirements:**
- Hybrid identity with password hash synchronization
- File shares accessible from Azure VMs using SMB protocol
- Web application must auto-scale between 2 and 10 instances based on CPU
- All web traffic must use HTTPS with a custom domain
- Administrators must connect to VMs without exposing public IPs
- Network security groups must restrict traffic between tiers
- Costs must be tracked per department using Azure governance features
- CPU alerts must notify the operations team within 5 minutes of threshold breach
- Backup policy: daily at 2 AM, 30-day retention, with ability to restore individual files

**Existing Azure resources:** A VNet named contoso-vnet with address space 10.0.0.0/16 and three subnets: web (10.0.1.0/24), app (10.0.2.0/24), data (10.0.3.0/24).`;

export const questionBank: QuestionSeed[] = [

  // ═══════════════════════════════════════════════════════════════
  // IDENTITY AND GOVERNANCE — 13 (3 easy, 7 medium, 3 hard)
  // ═══════════════════════════════════════════════════════════════

  {
    domain: DOMAINS.ID,
    skill: 'Manage Microsoft Entra users and groups',
    difficulty: 'easy',
    cognitiveLevel: 'apply',
    stem: 'Your organization needs to assign Microsoft 365 E5 licenses to 40 new employees. You must simplify future onboarding so that new hires automatically receive the same license without manual assignment. What should you do?',
    correct: ['Create a security group, assign the license to the group, and add the employees to the group'],
    distractors: [
      'Assign the license individually to each of the 40 users via the Microsoft 365 admin center',
      'Create a resource group in Azure and assign the license at the subscription scope',
      'Assign the Global Administrator role to all 40 employees so they inherit the license',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ID,
    skill: 'Assign roles at different scopes',
    difficulty: 'easy',
    cognitiveLevel: 'apply',
    stem: 'A support technician needs to restart VMs in a single resource group named RG-Prod-Web but must not be able to modify network settings or access other resource groups. You must follow the principle of least privilege. At which scope should you assign the Virtual Machine Contributor role?',
    correct: ['RG-Prod-Web resource group'],
    distractors: [
      'The root management group',
      'The entire Azure subscription',
      'Each individual VM within RG-Prod-Web',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ID,
    skill: 'Apply and manage tags on resources',
    difficulty: 'easy',
    cognitiveLevel: 'apply',
    stem: 'The finance team needs to generate monthly cost reports grouped by department. Each Azure resource must carry a department identifier that appears in Cost Management exports. Which governance feature should you apply?',
    correct: ['A tag with a key such as Department and the appropriate department value on each resource'],
    distractors: [
      'A ReadOnly resource lock on each resource',
      'A network security group rule tagging department names',
      'An Azure Policy that denies resource creation in all regions',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ID,
    skill: 'Manage external users',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'An external consultant using their own corporate email (consultant@partner.com) needs read-only access to a specific SharePoint site in your Microsoft Entra tenant for 30 days. You must not create a new username and password for them. What type of identity should you use?',
    correct: ['A B2B guest user invited to your Microsoft Entra tenant'],
    distractors: [
      'A system-assigned managed identity on a virtual machine',
      'A shared storage account key distributed to external parties',
      'A service endpoint configured on the SharePoint subnet',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ID,
    skill: 'Configure self-service password reset (SSPR)',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'Users must be able to reset their own passwords without calling the help desk. The security policy requires that users confirm two different authentication methods before resetting. Which configuration meets this requirement?',
    correct: ['Enable SSPR for the appropriate user group and require two authentication methods'],
    distractors: [
      'Configure password hash synchronization only, without enabling SSPR',
      'Apply an Azure Policy with a Deny effect on password changes',
      'Place a CanNotDelete lock on each user object in Microsoft Entra ID',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ID,
    skill: 'Implement and manage Azure Policy',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'New Azure resources must be blocked from deployment unless they are created in one of three approved Azure regions: East US, West Europe, or Southeast Asia. Resources deployed to any other region must be denied at creation time. What should you configure?',
    correct: ['An Azure Policy definition with the Deny effect specifying the allowed locations list'],
    distractors: [
      'A tag named AllowedRegion applied manually to each resource',
      'A budget alert set to 100% of the monthly spending limit',
      'An inbound NSG rule that filters traffic by region',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ID,
    skill: 'Configure resource locks',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'A production storage account named saprodstore01 contains critical data. It must not be deleted accidentally, but administrators still need to change its configuration settings, such as enabling soft delete and modifying firewall rules. Which lock type should you apply?',
    correct: ['A CanNotDelete lock on saprodstore01'],
    distractors: [
      'A ReadOnly lock at the subscription level',
      'A CanNotDelete lock on the Microsoft Entra tenant',
      'A ReadOnly lock on the development resource group',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ID,
    skill: 'Configure management groups',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'Your organization has five Azure subscriptions belonging to different departments: HR, Finance, Engineering, Sales, and Marketing. The same compliance policy must apply to all five subscriptions, and any new subscription added in the future must automatically inherit this policy. Where should the policy be assigned?',
    correct: ['At the management group that is the parent of all five subscriptions'],
    distractors: [
      'Directly on each individual user account in Microsoft Entra ID',
      'On the shared virtual network connecting the departments',
      'On the security group containing all department administrators',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ID,
    skill: 'Manage costs by using alerts, budgets',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'The cloud operations team wants to receive an email notification when the forecasted monthly spend reaches 80% of the defined budget limit, regardless of current actual spend. What should they create?',
    correct: ['An Azure budget with a forecast-based alert condition at 80% linked to an action group'],
    distractors: [
      'A ReadOnly lock on the billing scope to prevent overspend',
      'An Azure Policy that denies resources when cost exceeds 80%',
      'An Azure Service Health alert configured for the billing region',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ID,
    skill: 'Manage built-in Azure roles',
    difficulty: 'medium',
    cognitiveLevel: 'analyze',
    stem: 'An operations analyst needs to view all Azure resources, read monitoring data, and open support requests with Microsoft. However, they must NOT be able to create, modify, or delete any resource. Which combination of built-in roles at the subscription scope meets all requirements with least privilege?',
    correct: ['Reader plus Support Request Contributor'],
    distractors: [
      'Owner at the subscription scope',
      'User Access Administrator plus Virtual Machine Contributor',
      'Contributor at the subscription scope',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ID,
    skill: 'Assign roles at different scopes',
    difficulty: 'hard',
    cognitiveLevel: 'analyze',
    stem: 'A Contributor role is assigned to a Microsoft Entra security group at the subscription scope. Which two outcomes will occur as a result of this assignment?',
    correct: [
      'All current and future members of the group will inherit the Contributor role',
      'The role assignment will apply to every resource group and resource within the subscription',
    ],
    distractors: [
      'The assignment will override and remove all other role assignments for those users',
      'The Contributor role will also apply to resources in other subscriptions under the same tenant',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'multiple',
  },
  {
    domain: DOMAINS.ID,
    skill: 'Manage access to Azure resources',
    difficulty: 'hard',
    cognitiveLevel: 'apply',
    stem: 'No built-in Azure role grants exactly the permissions your team needs. You decide to create a custom role using Azure PowerShell. Which property of the custom role definition controls the subscriptions, resource groups, or management groups where this role can be assigned?',
    correct: ['assignableScopes'],
    distractors: [
      'notActions',
      'dataActions',
      'description',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ID,
    skill: 'Implement and manage Azure Policy',
    difficulty: 'hard',
    cognitiveLevel: 'apply',
    stem: 'You assign a policy with the DeployIfNotExists effect to ensure that all existing and new virtual machines have the Azure Monitor agent installed. Several VMs were created before the policy was assigned and lack the agent. What must you do to bring those existing VMs into compliance?',
    correct: ['Create a remediation task for the policy using a managed identity that has the necessary permissions'],
    distractors: [
      'Apply a ReadOnly lock to the non-compliant VMs until they self-remediate',
      'Move the non-compliant VMs to a different Azure subscription',
      'Create a budget alert to track the cost of the non-compliant VMs',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },

  // ═══════════════════════════════════════════════════════════════
  // STORAGE — 10 + 1 case study (2 easy, 5 medium, 3 hard)
  // ═══════════════════════════════════════════════════════════════

  {
    domain: DOMAINS.ST,
    skill: 'Configure Azure Files',
    difficulty: 'easy',
    cognitiveLevel: 'apply',
    stem: 'Two Windows Server VMs in the same virtual network need to mount a shared file system simultaneously using the SMB protocol. The solution must be fully managed and require no on-premises infrastructure. Which Azure service should you use?',
    correct: ['Azure Files with an SMB file share'],
    distractors: [
      'An Azure managed disk attached to both VMs simultaneously',
      'Azure Queue Storage with SMB tunneling enabled',
      'Azure Table Storage configured with a file share endpoint',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ST,
    skill: 'Configure storage tiers',
    difficulty: 'easy',
    cognitiveLevel: 'apply',
    stem: 'Blob data is read and written multiple times per day by a production application that requires sub-10ms latency. Which access tier should you select for this storage account?',
    correct: ['Hot tier'],
    distractors: [
      'Archive tier',
      'Cool tier with a lifecycle management policy',
      'Offline tier with manual rehydration',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ST,
    skill: 'Create and use SAS tokens',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'A vendor needs to upload files to a specific container in your Azure Storage account for a period of two hours. You must NOT share the storage account key. Which access method should you provide?',
    correct: ['A shared access signature (SAS) with write permission and a two-hour expiration'],
    distractors: [
      'The primary storage account key via encrypted email',
      'A connection string with no expiration set',
      'The Owner role assignment on the entire subscription',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ST,
    skill: 'Configure Azure Storage firewalls',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'A storage account must accept network access exclusively from the subnet named app-subnet within the VNet named prod-vnet. All other network access, including from the public internet, must be blocked. Which configuration should you apply?',
    correct: ['Enable the storage account firewall and add app-subnet to the allowed virtual network list'],
    distractors: [
      'Enable public network access from all networks',
      'Apply a tag named AllowedSubnet to the storage account',
      'Configure an Azure budget with a 100% threshold alert',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ST,
    skill: 'Configure Azure Storage redundancy',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'An application requires data to be synchronously replicated across three availability zones within the same Azure region. Which redundancy option should you select for the storage account?',
    correct: ['Zone-redundant storage (ZRS)'],
    distractors: [
      'Locally-redundant storage (LRS)',
      'Geo-redundant storage (GRS)',
      'Read-access geo-redundant storage (RA-GRS)',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ST,
    skill: 'Configure blob lifecycle management',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'Blobs that have not been modified for 90 days must be automatically moved from the Hot tier to the Cool tier to reduce storage costs. What should you configure?',
    correct: ['A lifecycle management rule with a filter based on days since last modification'],
    distractors: [
      'A stored access policy with a 90-day expiration',
      'An NSG rule that blocks access after 90 days',
      'An object replication policy from Hot to Cool',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ST,
    skill: 'Manage data using AzCopy',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'You need to copy a large directory tree containing thousands of files from an on-premises Windows server to an Azure Blob Storage container. The copy must be recursive, resume on failure, and run from a command-line script. Which tool should you use, and which flag is essential?',
    correct: ['AzCopy with the copy command and the --recursive flag'],
    distractors: [
      'Azure DNS CLI with the zone-export flag',
      'Network Watcher packet capture with the --deep-inspect flag',
      'The Bicep decompile command targeting the storage account',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ST,
    skill: 'Configure stored access policies',
    difficulty: 'hard',
    cognitiveLevel: 'analyze',
    stem: 'You have issued multiple service-level SAS tokens to different clients for the same container. A security incident requires you to immediately revoke all of these SAS tokens without rotating the storage account keys, which would also disrupt other services. How should you have created the SAS tokens to enable this?',
    correct: ['Associate all SAS tokens with a stored access policy on the container, which can be deleted or modified to revoke access'],
    distractors: [
      'Create only user-delegation SAS tokens with no expiration',
      'Enable anonymous public access on the container',
      'Copy the primary storage account key to each client and monitor usage',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.ST,
    skill: 'Configure object replication',
    difficulty: 'hard',
    cognitiveLevel: 'apply',
    stem: 'You plan to configure object replication between two Azure storage accounts to asynchronously copy block blobs from a source account in East US to a destination account in West Europe. Which two features must be enabled before configuring the replication policy?',
    correct: [
      'Blob versioning on both the source and destination accounts',
      'Change feed on the source account',
    ],
    distractors: [
      'NFS 3.0 protocol on both storage accounts',
      'Anonymous public access on the destination container',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'multiple',
  },
  {
    domain: DOMAINS.ST,
    skill: 'Configure storage account encryption',
    difficulty: 'hard',
    cognitiveLevel: 'apply',
    stem: 'Your security policy requires that you control, rotate, and audit the encryption keys used to encrypt data at rest in your Azure Storage account. Microsoft-managed keys are not acceptable. What should you configure?',
    correct: ['Customer-managed keys stored in Azure Key Vault with the key URI referenced in the storage account encryption settings'],
    distractors: [
      'An account-level SAS token used as an encryption key',
      'An SSH public key uploaded to each virtual machine using the storage account',
      'A TLS/SSL certificate bound to the storage account custom domain',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },

  // ═══════════════════════════════════════════════════════════════
  // COMPUTE — 12 + 1 case study (3 easy, 6 medium, 3 hard)
  // ═══════════════════════════════════════════════════════════════

  {
    domain: DOMAINS.CO,
    skill: 'Provision containers using ACI',
    difficulty: 'easy',
    cognitiveLevel: 'apply',
    stem: 'You need to run a single, stateless container workload for batch processing that starts on demand and terminates after completion. You do NOT want to manage any virtual machines, Kubernetes clusters, or container orchestration platforms. Which Azure service should you choose?',
    correct: ['Azure Container Instances'],
    distractors: [
      'Azure Virtual Desktop with a container host pool',
      'Azure DNS with a private resolver',
      'Azure Files with a container export share',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.CO,
    skill: 'Create an App Service',
    difficulty: 'easy',
    cognitiveLevel: 'apply',
    stem: 'A development team needs to host a web application without managing the underlying operating system, web server, or infrastructure patching. The application must support automatic OS updates and platform-managed TLS certificates. Which Azure service should you provision?',
    correct: ['Azure App Service'],
    distractors: [
      'Azure VPN Gateway with application proxy',
      'Azure Route Server with a web route',
      'Azure Backup vault with a recovery plan',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.CO,
    skill: 'Deploy VMs to availability zones',
    difficulty: 'easy',
    cognitiveLevel: 'apply',
    stem: 'You deploy two virtual machines running a stateless web application. The solution must tolerate a complete datacenter failure within an Azure region. How should the VMs be distributed?',
    correct: ['Deploy each VM to a different availability zone within the same region'],
    distractors: [
      'Place both VMs in the same availability set in a single zone',
      'Attach the same OS disk to both VMs simultaneously',
      'Deploy both VMs to the same proximity placement group',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.CO,
    skill: 'Deploy and configure VM Scale Sets',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'A web application runs on a Virtual Machine Scale Set. When average CPU utilization exceeds 70% for 10 minutes, the instance count should increase automatically. When CPU drops below 30% for 10 minutes, instances should decrease. What should you configure?',
    correct: ['An autoscale rule on the scale set with scale-out and scale-in conditions based on CPU percentage'],
    distractors: [
      'A blob lifecycle management rule on the OS disk',
      'An Azure Policy with an Audit effect on the scale set',
      'A DNS alias record that load balances between instances',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.CO,
    skill: 'Manage virtual machine disks',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'A SQL Server virtual machine requires sub-millisecond latency and consistently high IOPS for its data disks. The workload is performance-sensitive and cannot tolerate throttling during peak hours. Which disk type should you choose?',
    correct: ['Premium SSD v2 managed disks with provisioned IOPS and throughput'],
    distractors: [
      'Standard HDD with host-level caching enabled',
      'Archive-tier blob storage mounted as a virtual disk',
      'Azure Files Cool tier share mapped as a network drive',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.CO,
    skill: 'Deploy resources using Bicep files',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'You are writing a Bicep file that deploys an App Service. The environment name (dev, test, prod) must be provided at deployment time so that the same Bicep file can be used across all environments. How should you handle this in the Bicep code?',
    correct: ['Declare a parameter using the param keyword and reference it in the resource definitions'],
    distractors: [
      'Define an output without a corresponding input',
      'Create an NSG rule named after the environment',
      'Use a stored access policy to store the environment name',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.CO,
    skill: 'Create and manage ACR',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'Your team is building containerized microservices. Container images must be stored in a private registry located in the same Azure region as your AKS cluster to minimize pull latency. Which resource should you create?',
    correct: ['An Azure Container Registry in the same region as the AKS cluster'],
    distractors: [
      'A Recovery Services vault with container backup enabled',
      'An Azure Application Gateway with a container health probe',
      'An Azure DNS private resolver with a container zone',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.CO,
    skill: 'Configure deployment slots',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'Your team deploys a new version of a web app to production. Before directing production traffic to the new version, you must validate it in a staging environment. After validation, the swap must happen instantly with no cold start. What should you use?',
    correct: ['A deployment slot named staging, validate the app there, then perform a slot swap with the production slot'],
    distractors: [
      'Delete and recreate the App Service plan for each deployment',
      'Modify the DNS zone A record to point to a staging VM before each release',
      'Create an entirely new Azure subscription for each deployment cycle',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.CO,
    skill: 'Configure App Service scaling',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'An App Service must run on three instances during business hours (8 AM to 6 PM) and scale down to one instance overnight and on weekends. Which configuration change is required?',
    correct: ['Modify the instance count of the App Service plan, either manually or via a scale rule with a schedule'],
    distractors: [
      'Increase the number of resource groups containing the App Service',
      'Change the Log Analytics workspace retention period',
      'Upgrade the SKU of the Azure VPN Gateway',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.CO,
    skill: 'Move VMs between subscriptions',
    difficulty: 'hard',
    cognitiveLevel: 'analyze',
    stem: 'You need to move a virtual machine from one Azure subscription to another. The VM has a managed OS disk, a data disk, and a network interface. Which two prerequisites must be verified before initiating the move?',
    correct: [
      'Both subscriptions must belong to the same Microsoft Entra tenant',
      'All dependent resources (disks, NICs) must be moved together or handled appropriately',
    ],
    distractors: [
      'The VM must use an unmanaged disk attached via a storage account',
      'Both subscriptions must have exactly the same display name in the Azure portal',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'multiple',
  },
  {
    domain: DOMAINS.CO,
    skill: 'Map custom DNS to App Service',
    difficulty: 'hard',
    cognitiveLevel: 'apply',
    stem: 'You need to configure the custom domain www.contoso.com for an App Service without causing downtime for the existing website. The domain is registered with a third-party registrar. Which DNS record type does App Service require you to create to verify domain ownership?',
    correct: ['A TXT record with the domain verification ID provided by the App Service custom domain blade'],
    distractors: [
      'A PTR record pointing to the private IP address of the App Service',
      'An SRV record on port 3389 for RDP verification',
      'An NS record delegating the domain to the VM public IP',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.CO,
    skill: 'Deploy resources using Bicep files',
    difficulty: 'hard',
    cognitiveLevel: 'apply',
    stem: 'You have a Bicep file that must create five identical storage accounts based on an array of storage account names. You want to avoid duplicating the resource declaration five times. Which Bicep construct should you use?',
    correct: ['A for-loop on the resource declaration iterating over the array of names'],
    distractors: [
      'Copy and paste the resource declaration five times with different names',
      'An if condition that always evaluates to false to skip duplicates',
      'An output statement that generates one character of each name at a time',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },

  // ═══════════════════════════════════════════════════════════════
  // NETWORKING — 9 + 1 case study (2 easy, 5 medium, 2 hard)
  // ═══════════════════════════════════════════════════════════════

  {
    domain: DOMAINS.NW,
    skill: 'Create and configure NSGs',
    difficulty: 'easy',
    cognitiveLevel: 'apply',
    stem: 'A subnet hosts web servers that must accept HTTPS traffic from the internet. All other inbound ports must remain blocked. Which NSG rule should you create?',
    correct: ['An inbound rule allowing TCP destination port 443 with source set to Internet'],
    distractors: [
      'A user-defined route that sends HTTPS traffic to a virtual appliance',
      'A blob lifecycle management rule filtering HTTPS requests',
      'A service-level SAS token bound to port 443',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.NW,
    skill: 'Configure virtual network peering',
    difficulty: 'easy',
    cognitiveLevel: 'apply',
    stem: 'Two virtual networks in the same Azure region need to communicate with each other using private IP addresses over the Microsoft backbone network with minimal latency. No VPN gateways should be deployed. Which connectivity method should you use?',
    correct: ['Virtual network peering between the two VNets'],
    distractors: [
      'Azure Files with a shared file system',
      'An Azure Policy that allows cross-VNet traffic',
      'A Recovery Services vault with network integration',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.NW,
    skill: 'Configure private endpoints',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'An application running on a VM in a VNet must access an Azure Storage account using a private RFC 1918 IP address. Public network access on the storage account must be disabled entirely. Which resource should you create?',
    correct: ['A private endpoint for the storage account in the same VNet and subnet as the application VM'],
    distractors: [
      'A public IP address with a Standard SKU',
      'A service tag named Internet on the storage account firewall',
      'An inbound NAT rule on the VM public load balancer',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.NW,
    skill: 'Implement Azure Bastion',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'Administrators need to connect via RDP and SSH to virtual machines that do NOT have public IP addresses. The connection must be made through the Azure portal over TLS. Which service provides this capability?',
    correct: ['Azure Bastion deployed in the same VNet as the VMs'],
    distractors: [
      'Azure Front Door with RDP/SSH health probes',
      'Azure CDN with a remote desktop endpoint',
      'Azure Blob Storage with an RDP container',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.NW,
    skill: 'Configure user-defined routes',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'All outbound internet-bound traffic from the app-subnet must be inspected by a network virtual appliance (NVA) before reaching the internet. The NVA is deployed in a different subnet within the same VNet. What must you configure?',
    correct: ['A route table with a route for 0.0.0.0/0 whose next hop type is Virtual Appliance, pointing to the NVA IP, and associate it with app-subnet'],
    distractors: [
      'A CNAME DNS record that maps internet traffic to the NVA',
      'An Azure Policy with an Append effect enforcing the NVA path',
      'A blob lifecycle rule that redirects traffic after 90 days',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.NW,
    skill: 'Configure load balancer',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'Three backend VMs in a VNet must receive evenly distributed TCP traffic on port 80 from other services within the same VNet. The load balancer must NOT be exposed to the internet. Which solution should you deploy?',
    correct: ['An internal Azure Load Balancer with a backend pool containing the three VMs and a health probe on port 80'],
    distractors: [
      'A public DNS zone without any load balancer configuration',
      'A Recovery Services vault with a network rule',
      'A management group with a network access policy',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.NW,
    skill: 'Configure Azure DNS',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'You need to host the public DNS zone for contoso.com authoritatively in Azure. The domain is registered with a third-party registrar. What steps are required?',
    correct: ['Create a public DNS zone named contoso.com in Azure, then update the name servers at the domain registrar with the Azure DNS name servers listed in the zone'],
    distractors: [
      'Create a private DNS zone and link it to every VNet in the subscription',
      'Associate an NSG with the domain name at the registrar',
      'Create a managed identity with DNS Contributor permissions',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.NW,
    skill: 'Evaluate effective security rules',
    difficulty: 'hard',
    cognitiveLevel: 'analyze',
    stem: 'A VM is not receiving traffic that appears to be allowed by a subnet-level NSG rule. You need to troubleshoot by examining the effective security rules for the VM. Which two locations should you check to fully understand why traffic is being blocked?',
    correct: [
      'The NSG associated directly with the network interface of the VM',
      'The default security rules and priority ordering across all applicable NSGs',
    ],
    distractors: [
      'The tags on the storage account in the same resource group',
      'The backup policy configuration for the VM',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'multiple',
  },
  {
    domain: DOMAINS.NW,
    skill: 'Configure VNet peering',
    difficulty: 'hard',
    cognitiveLevel: 'analyze',
    stem: 'VNet-A is peered with VNet-B. VNet-B is peered with VNet-C. A VM in VNet-A must communicate directly with a VM in VNet-C without routing through VNet-B. What is required?',
    correct: ['Create a direct peering between VNet-A and VNet-C, because VNet peering is not transitive by default'],
    distractors: [
      'No action is needed because peering is automatically transitive across all peered VNets',
      'Create an identical tag on all three VNets to enable transitive routing',
      'Move all three VNets into the same resource group to enable transitive connectivity',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },

  // ═══════════════════════════════════════════════════════════════
  // MONITORING AND RECOVERY — 7 + 1 case study (1 easy, 3 medium, 3 hard)
  // ═══════════════════════════════════════════════════════════════

  {
    domain: DOMAINS.MO,
    skill: 'Interpret metrics in Azure Monitor',
    difficulty: 'easy',
    cognitiveLevel: 'apply',
    stem: 'You need to view the average CPU utilization of a production VM over the past hour to diagnose performance issues. Where should you look?',
    correct: ['Azure Monitor Metrics for the VM, selecting the Percentage CPU metric with a one-hour time range'],
    distractors: [
      'Azure Policy compliance dashboard',
      'Cost Management cost analysis export',
      'Microsoft Entra ID sign-in logs',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.MO,
    skill: 'Set up alert rules and action groups',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'When a CPU alert fires for any production VM, the operations team must receive both an email and a webhook call to their incident management system. What should you associate with the alert rule?',
    correct: ['An action group that contains both an email notification action and a webhook action'],
    distractors: [
      'A route table with email and webhook next-hop types',
      'A stored access policy with email and webhook permissions',
      'A deployment slot that sends notifications',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.MO,
    skill: 'Query and analyze logs',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'Multiple VMs send their diagnostic logs to the same Log Analytics workspace. You need to find all error-level events from these VMs in the last 30 minutes. What should you use?',
    correct: ['A Kusto Query Language (KQL) query in the Log Analytics workspace filtering by severity level and time range'],
    distractors: [
      'An inbound NAT rule on the Azure Load Balancer',
      'A resource tag applied to the resource group',
      'A TXT record query in Azure DNS',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.MO,
    skill: 'Create and configure backup policy',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'A production VM must be backed up daily at 2:00 AM, with backups retained for 30 days before automatic deletion. Which two Azure resources must you configure?',
    correct: [
      'A Recovery Services vault',
      'A backup policy with daily schedule and 30-day retention',
    ],
    distractors: [
      'An NSG with a 30-day retention rule',
      'A blob lifecycle management rule on the OS disk',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'multiple',
  },
  {
    domain: DOMAINS.MO,
    skill: 'Configure log settings',
    difficulty: 'hard',
    cognitiveLevel: 'apply',
    stem: 'You need to send all Azure Activity Log entries from your subscription to a Log Analytics workspace for long-term retention and querying, including administrative operations and service health events. What should you create?',
    correct: ['A diagnostic setting on the subscription configured to stream the required log categories to the Log Analytics workspace'],
    distractors: [
      'A SAS token for the Log Analytics workspace public endpoint',
      'An availability set containing the subscription resources',
      'A custom DNS name mapped to the Log Analytics workspace IP',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },
  {
    domain: DOMAINS.MO,
    skill: 'Configure Azure Site Recovery',
    difficulty: 'hard',
    cognitiveLevel: 'analyze',
    stem: 'You are configuring Azure Site Recovery to replicate production VMs from East US to West US for disaster recovery. Which two configurations are essential components of the disaster recovery plan?',
    correct: [
      'Replication settings that specify the target region and recovery network',
      'A recovery plan that defines the failover order and any post-failover scripts for the VMs',
    ],
    distractors: [
      'Anonymous public access enabled on the VMs for replication traffic',
      'Owner role assigned to every user in Microsoft Entra ID',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'multiple',
  },
  {
    domain: DOMAINS.MO,
    skill: 'Perform backup and restore operations',
    difficulty: 'hard',
    cognitiveLevel: 'apply',
    stem: 'A VM was accidentally misconfigured, but its data disk contains critical files. You have a valid Azure Backup recovery point from the previous night. You need to retrieve only specific files from the recovery point without overwriting the current VM or its OS disk. Which operation should you choose?',
    correct: ['File recovery from the recovery point using Azure Backup, which mounts the snapshot as a local volume for file extraction'],
    distractors: [
      'Full VM restore that replaces the existing VM entirely',
      'A planned Site Recovery failover to the secondary region',
      'Redeploy the entire Azure subscription',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
  },

  // ═══════════════════════════════════════════════════════════════
  // CASE STUDY: Contoso Ltd. — 4 items (2 medium, 2 hard)
  // ═══════════════════════════════════════════════════════════════

  {
    domain: DOMAINS.ST,
    skill: 'Configure Azure Files',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'Contoso Ltd. needs to migrate their 5 TB of department file shares to Azure. Multiple Azure VMs across different subnets must mount the shares simultaneously using SMB. Which Azure service should Contoso provision?',
    correct: ['An Azure Files share in a storage account, mounted via SMB on the Azure VMs'],
    distractors: [
      'An Azure managed disk attached individually to each VM',
      'Azure Queue Storage configured for file synchronization',
      'Azure Table Storage with an SMB gateway enabled',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
    caseStudyId: 'contoso',
    caseStudyPrompt: CASE_STUDY_PROMPT,
  },
  {
    domain: DOMAINS.CO,
    skill: 'Configure App Service scaling',
    difficulty: 'medium',
    cognitiveLevel: 'apply',
    stem: 'Contoso\'s three-tier web application must automatically scale between 2 and 10 instances based on CPU utilization, as specified in their requirements. Where should the autoscale settings be configured?',
    correct: ['On the App Service Plan associated with the web application, defining scale-out and scale-in rules based on CPU percentage'],
    distractors: [
      'On the Azure DNS zone serving the contoso.com domain',
      'On the network security group protecting the web subnet',
      'On the Recovery Services vault backup policy',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
    caseStudyId: 'contoso',
    caseStudyPrompt: CASE_STUDY_PROMPT,
  },
  {
    domain: DOMAINS.NW,
    skill: 'Implement Azure Bastion',
    difficulty: 'hard',
    cognitiveLevel: 'apply',
    stem: 'Per Contoso\'s security requirements, administrators must connect to VMs without exposing public IP addresses. The contoso-vnet already exists with three subnets. Which service should be deployed, and what is a prerequisite?',
    correct: ['Azure Bastion, which requires a dedicated subnet named AzureBastionSubnet with at least a /26 address range within contoso-vnet'],
    distractors: [
      'Azure Front Door with a backend pool containing all VMs',
      'Azure CDN with a point-to-site VPN endpoint',
      'An Azure Storage account with an RDP file share',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'single',
    caseStudyId: 'contoso',
    caseStudyPrompt: CASE_STUDY_PROMPT,
  },
  {
    domain: DOMAINS.MO,
    skill: 'Set up alert rules',
    difficulty: 'hard',
    cognitiveLevel: 'apply',
    stem: 'Contoso requires that the operations team be notified within 5 minutes when any VM CPU exceeds 90%, as stated in their monitoring requirements. Which two Azure components must be configured to meet this requirement?',
    correct: [
      'An alert rule with a static threshold of 90% CPU and an evaluation frequency of 1 minute',
      'An action group containing email and/or webhook notification actions',
    ],
    distractors: [
      'A blob lifecycle rule on the VM diagnostic storage',
      'A DNS CNAME record pointing to the monitoring endpoint',
    ],
    sourceUrl: STUDY_GUIDE,
    type: 'multiple',
    caseStudyId: 'contoso',
    caseStudyPrompt: CASE_STUDY_PROMPT,
  },
];
